export const personalData = {
  firstName: "Chuthuka",
  lastName: "Dedunu Hettiarachchi",
  fullName: "Chuthuka Dedunu Hettiarachchi",
  age: 23,
  illustration : "/assets/images/photos/profile_Illustration.png",
  profilePic: "/assets/images/photos/ProfilePic.jpg",
  location: "Kiribathgoda, Sri Lanka",
  email: "chuthuka097dedunu@gmail.com",
  phone: "+94 76 645 3116",
  education: "SUS Undergraduate | Software Engineering Intern",
  bio: "Hi, I'm Chuthuka Dedunu Hettiarachchi, a passionate 23-year-old Software Engineering Intern from Kiribathgoda, Sri Lanka. I am currently pursuing my Bachelor's degree in Computing & Information Systems at the Sabaragamuwa University of Sri Lanka (SUSL).With hands-on internship experience and a strong interest in developing innovative software solutions, I strive to combine creativity and technical expertise to build impactful and user-friendly applications. My goal is to contribute to projects that solve real-world problems while continuously learning and growing as a software engineer.",
  socialLinks: {
    github: "https://www.github.com/Chuthuka/",
    linkedin: "https://www.linkedin.com/in/chuthuka-dedunu1",
    facebook: "https://www.facebook.com/share/1CUeGiUCna/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/nipun__s/",
    whatsapp: "https://wa.me/94766453116",
  },
  roles: [
    "Software Engineering Intern",
    "Full Stack Developer",
    "Java Developer",
    "React Developer",
    "Angular Developer",
    "Spring Boot Developer",
    "Problem Solver",
    "Aspiring Data Analyst",
    "Aspiring Data Scientist",
    "Aspiring Data Engineer"
  ],
  experience: "2+",
};

export const mainSkillAreas = [
  {
    title: "Frontend Development",
    icon: "Monitor",
    description:
      "Crafting responsive, accessible, and visually engaging user interfaces using modern frameworks and libraries.",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Angular",
      "Bootstrap",
      "Tailwind CSS",
      "TypeScript",
      "SASS",
      "jQuery",
      "Figma",
    ],
  },
  {
    title: "Backend & Databases",
    icon: "Server",
    description:
      "Building robust backend systems and managing relational and NoSQL databases for scalable applications.",
    skills: [
      "Java",
      "Spring Boot",
      "PHP",
      "Node.js",
      "Python",
      "RESTful APIs",
      "JPA",
      "Hibernate",
      "MySQL",
      "MongoDB",
      "SQL",
    ],
  },
  {
    title: "Mobile & Cloud Technologies",
    icon: "Smartphone",
    description:
      "Developing mobile applications and integrating cloud-based services for seamless, real-time access.",
    skills: [
      "Android Studio",
      "React Native",
      "Firebase",
      "Git",
      "Docker",
      "AWS",
      "Kotlin",
      "CI/CD",
      "REST APIs",
    ],
  },
  {
    title: "Tools & Methodologies",
    icon: "Settings",
    description:
      "Applying agile workflows and leveraging modern tools to streamline development and collaboration.",
    skills: [
      "Postman",
      "Agile Methodology",
      "JIRA",
      "VS Code",
      "IntelliJ IDEA",
      "GitHub",
      "Trello",
      "Maven",
      "Scrum",
      "Google Colab",
      "SQL Server / MySQL",
      "MongoDB",
      "Power BI",
      "Tableau",
      "Excel",
      "Git for version control",
      "Docker (for data apps)",
      "Data Visualization",
    ],
  },
];

export const projectsData = [
  {
    title: "HR Management System",
    description: "Full-featured HR system with secure login and Angular Material UI.",
    image: "/assets/images/projects/hrmanagement.webp",
    tags: ["Spring Boot", "JPA", "Angular", "Angular Material"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Task Manager Application",
    description: "Full-stack task manager app with JWT authentication and Docker.",
    image: "/assets/images/projects/taskmanager.webp",
    tags: ["Spring Boot", "JPA", "Angular", "Docker"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Java Microservices with Kafka",
    description: "Event-driven system with 3 microservices using Spring Boot.",
    image: "/assets/images/projects/microservices.webp",
    tags: ["Spring Boot", "Apache Kafka", "Microservices", "Java"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "backend",
    featured: true,
    viewButton: false,
  },
  {
    title: "Digital Tug Of War Game",
    description: "Real-time multiplayer game using React and WebSocket.",
    image: "/assets/images/projects/tugofwar.webp",
    tags: ["ReactJS", "Spring Boot", "WebSocket", "Java"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "MOS Burgers Ordering System",
    description: "Ordering system for MOS Burgers with REST APIs.",
    image: "/assets/images/projects/mosburgers.webp",
    tags: ["Spring Boot", "JPA", "HTML", "Bootstrap"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Clothify Store POS System",
    description: "JavaFX-based POS system for clothing stores.",
    image: "/assets/images/projects/clothify.webp",
    tags: ["JavaFX", "Hibernate", "Google Guice"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "desktop",
    featured: true,
    viewButton: false,
  },
  {
    title: "ChatterAI",
    description: "AI chatbot using Gemini AI with a modern UI.",
    image: "/assets/images/projects/chatterai.webp",
    tags: ["HTML", "CSS", "JavaScript", "AI"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: true,
  },
  {
    title: "Vehicle Service Management System",
    description: "Web app to manage vehicle services using PHP and MySQL.",
    image: "/assets/images/projects/service.webp",
    tags: ["PHP", "JavaScript", "HTML", "MySQL"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: true,
  },
  {
    title: "Checkmate 3D",
    description: "3D chess game using Three.js and Stockfish engine.",
    image: "/assets/images/projects/checkmate3d.webp",
    tags: ["Three.js", "JavaScript", "3D Graphics", "WebGL"],
    demoLink: "",
    codeLink: "https://github.com/Chuthuka",
    category: "web",
    featured: true,
    viewButton: true,
  },
];

export const certificationsData = [
 {
    "title": "Artificial Intelligence (AI) Workshop",
    "issuer": "BuilderX",
    "date": "30th August 2025",
    "description": "This certificate confirms that C. D. Hettiarachchi participated in and successfully completed the Artificial Intelligence (AI) Workshop.",
    "badge": "/assets/images/certifications/C.D. Hettiarachchi_1.jpg",
    "verificationLink": "https://builderx.lk/verify"
},
  {
    "title": "AI For All",
    "issuer": "Intel and CBSE",
    "date": "20th August 2025",
    "description": "This is to certify that C. D. Hettiarachchi has successfully completed the AI for All Programme jointly organised by Intel and CBSE.",
    "badge": "/assets/images/certifications/C.D. Hettiarachchi_2.jpg",
    "verificationLink": "https://www.credly.com/go/9dZyqSt8muihsdGopF8kdQ"
},
  {
    title: "Postman API Student Expert",
    issuer: "Postman",
    date: "March 2025",
    description: "Validated core API development skills using Postman tools.",
    badge: "/assets/images/certifications/Postman API Fundamentals Student Expert.png",
    verificationLink: "https://badgr.com/public/assertions/nTENLduoTBCkvJ3Mo9qdJg?identity__email=cdhettiarachchi@std.foc.sab.ac.lk",
  },
  {
    "title": "Work with Components in Figma",
    "issuer": "Coursera Project Network",
    "date": "14th March 2025",
    "description": "This guided project verifies that C. D. Hettiarachchi successfully completed the hands-on project 'Work with Components in Figma' and can demonstrate proficiency in the specified topic.",
    "badge": "/assets/images/certifications/C.D. Hettiarachchi_3.jpg",
    "verificationLink": "https://www.coursera.org/account/accomplishments/verify/H6BT682W7RPQ"
},
 {
    "title": "Web Design for Beginners",
    "issuer": "University of Moratuwa - Centre for Open & Distance Learning",
    "date": "11th December 2023",
    "description": "This certificate verifies that C. D. Hettiarachchi successfully completed the online learning program in Web Design for Beginners.",
    "badge": "/assets/images/certifications/C.D. Hettiarachchi_6.jpg",
    "verificationLink": "https://open.uom.lk/lms/mod/customcert/verify_certificate.php/wxZv2EPQe6"
},
  {
    "title": "Power BI for Beginners",
    "issuer": "Simplilearn",
    "date": "July 01, 2024",
    "description": "This certificate recognizes C. D. Hettiarachchi for successfully completing the Power BI for Beginners training program.",
    "badge": "/assets/images/certifications/C.D. Hettiarachchi_5.jpg",
    "verificationLink": "https://simpli-web.app.link/e/qaPHNIaUMVb"
},
];

export const sectionsData = {
  hero: {
    subtitle: "Welcome to my portfolio",
    ctaButtons: [
      {
        text: "View My Work",
        link: "#projects",
        type: "primary",
      },
      {
        text: "Contact Me",
        link: "#contact",
        type: "outline",
      },
    ],
  },
  about: {
    title: "About Me",
    subtitle: "Software Engineering Intern | SUSL Undergraduate",
    ctaButtons: [
      {
        text: "Download CV",
        link: "/assets/cv/chuthuka_dedunu_resume.pdf",
        type: "primary",
        id: "download-cv",
      },
      {
        text: "Get In Touch",
        link: "#contact",
        type: "outline",
      },
    ],
  },
  skills: {
    title: "My Skills",
    subtitle: "A showcase of my technical expertise and proficiency",
  },
  projects: {
    title: "My Projects",
    subtitle: "Check out some of my recent work",
    categories: ["all", "web", "mobile", "desktop"],
  },
  certifications: {
    title: "Certifications",
    subtitle: "Professional certifications and achievements",
  },
  contact: {
    title: "Get In Touch",
    subtitle: "Feel free to contact me for any project or collaboration",
    heading: "Let's Talk",
    description:
      "Have a project in mind or want to collaborate? Reach out using any of the methods below.",
  },
};